services:
  - type: worker
    name: telegram-screenshot-bot
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
